### ISSUE TITLE
Support for HTML5/JS application

### ISSUE THREAD

**Issue by akranga** [agilestacks/applications#2]
I as a user want to generate an HTML5/JavaScript application with S3 and CloudFront distribution
- [x] Implement professionally looking application with ReactJS 
- [x] Create necessary components for AWS S3, CloudFront and R53
- [x] Implement support on this new type of app in reactor and automation hub
- [x] Implement applications generation 

UI should include:
- [x] user should be able to define her domain name (subdomain of the cloud account with default: `${app-name}.${base}`
- [ ] user should be able to decide wether she wants or don't wants to use cloudfront distribution

Sample Manifest for application
```yaml
version: 1
kind: application
meta:
  name: chuckNorris
  toolbox: docker.io/agilestacks/toolbox:stable
  brief: >-
    HTML5 and JavaScript application, deployed by 
    Jenkins CI as S3 hosted website with CloudFront distribution
requires: # these capablities must provide stack that will carry the application
- aws
components:
- name: github-repo # creates github repository
  source: TBD
- name: java-template # pulls java template into github repository
  source: https://github.com/agilestacks/application-templates.git//reactjs-template
- name: jenkins-operator # jenkins operator creates pipeline
  source: TBD
lifecycle:
  order:
  - ecr
  - github-repo
  - jenkins-operator
parameters:
- name: app.name
  value: APPLICATION_NAME
- name: dns.domain
- name: component.github.operator
  parameters:
  - name: deployKey
    fromEnv: GITHUB_DEPLOY_KEY # deploykey from environment
  - name: api
    value: "https://api.github.com"
  - name: organization
    value: agilestacks
  - name: name
    value: chuck-norris
- name: component.jenkins.operator
  parameters:
  - name: master.fqdn
    fromEnv: JENKINS_FQDN
  - name: username
    fromEnv: JENKINS_USERNAME
  - name: password
    fromEnv: JENKINS_PASSWORD
- name: component.jenkins.pipeline
  parameters:
  - name: sourceUrl
    value: "${component.github.operator.repository}"
  - name: credentials.name
    value: chucknorris-github
  - name: credentials.secret
    fromEnv: GITHUB_DEPLOY_KEY # deploykey from environment
  - name: pipeline
    name: Jenkinsfile
outputs:
- name: application.chuckNorris.fqdn
  brief: >-
    Fully qualified domain name how to access application
    after successful deployment
```
