### ISSUE TITLE
Phase 0 design

### ISSUE THREAD

**Issue by akranga** [agilestacks/applications#30]
Phase 0 has been responsible for Application code generation. It is is relatively simple and carried out as init container for application provisioning Kubernetes Job (Phase 1). 

As the input init container takes two files `phase0.yaml` and `hub.yaml`.

- `.phase0/hub.yaml` describes git path (`hub pull`) to application [template](https://github.com/agilestacks/applications/tree/master/app-templates), as well to all required components. Components can be fretched from: [applications/components](https://github.com/agilestacks/applications), [components](http://github.com/agilestacks/components), [agilestcks-components](https://github.com/agilestacks/agilestacks-components), (other urls?)

- `hub.yaml` this is a ready to consume by Phase 1 hub.yaml that must be copied into the root of application workspace

### Git secret
Git secret has been passed as `GITHUB_TOKEN` environment variable

### Prerequisites
Automation hub should submit manifestests to phase0 and phase1 to the File Service with TTL 5 minutes or so. Then it will put download URLs as environment variables for phase0 container. and start application provisioning job

### Execution Steps
0. Start init container with empty workspace (`emptyDir` volume?)
1. Download with `curl` requried manifests for phase0 and phase1
2. Proceed with phase 0
3. Download all components described in phase0 maifest
4. Render all application templates (described in `phase0.yaml`)
5. Delete all irrelevant components from workspace
6. Delete `.phase0`
7. Pass workspace to phase1 container 

## Phase 0 manifest
Describes where to find necessary components
```yaml
---
version: 1
kind: template
meta:
  name: argo:1
  brief: >
    Argo worfklow application with s3 trigger
  source:
    git:
      remote: http://github.com/agilestacks/applications.git
      subDir: /app-templates/argo
components:
- name: argo-trigger
  source:
    git:
      remote: http://github.com/agilestacks/applications.git
      subDir: components/argo-trigger
      localDir: components/argo-trigger
```

### Phase 1 manifest
Describes how to execute application 
```
---
version: 1
kind: application
meta:
  name: argo:1
  brief: >
    Argo worfklow application with s3 trigger
  source:
    dir: .
components:
- name: argo-trigger
  source:
    dir: components/argo-trigger

parameters:
- name: component.argo.trigger.s3
  value: xyz
```

## Application Worspace
`.phase0/hub.yaml`  - hub manifest for phase0
`.phase0/*.template` - templates rendered during phase0
`components/` - directory for application components
`templates/` - directory for application templates (rendered at phase 0)
`hub.yaml` - hub manifest for phase 1
`other application template artifacts`
