### ISSUE TITLE
Incorrect parameters for reactjs application

### ISSUE THREAD

**Issue by akranga** [agilestacks/applications#9]
Steps to reproduce
1. create new application screen
2. select reactjs
3. scroll down 
4. see screenshot

Application offers to create an ingress. As we speak we support scenario when we create an S3 bucket (which must have different name than ingress). Instead screen should offer the following:

- [] Two input parameters: <app-name>.cloud.domain/<app-context-path>

see `hub.yaml` for info
```yaml
#...
parameters:
#...
- name: component.s3webiste
  parameters:
  - name: name
    fromEnv: APPLICATION_NAME
  - name: baseDomain
    value: ${dns.domain}
  - name: bucket
  - name: endpoint
#...
```

![Screen Shot 2018-07-03 at 1.43.18 PM.png](https://images.zenhubusercontent.com/58e3ab9751aa2c30577a5804/eebf6db8-6bea-491a-b23e-910f023a42f5)
